### ISSUE TITLE
ValueError when parsing PREFIX containing '#'

### ISSUE THREAD

**Issue by plbt5** [Jeroen537/parser#11]
Ik weet niet of het niet is toegestaan, maar neem de volgende sparql query:
```
# query op ontoTemp1A
PREFIX    ontoA:    <http://ts.tno.nl/mediator/1.0/examples/ontoTemp1A#>
PREFIX    rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?p ?v
WHERE {
    ?p rdf:type ontoA:Patient .
    ?p ontoA:hasTemp ?v
    FILTER (?v > 37.0)
}
```
Daar valt de sparqlparser over, als volgt:
```
Traceback (most recent call last):
  File "C:\Users\brandtp\AppData\Local\My Local Documents\My\Workspaces\ParserScrapbook\src\root\nested\sparlparserKlad.py", line 35, in <module>
    r = sparqlparser.parseQuery(q)
  File "C:\Users\brandtp\AppData\Local\My Local Documents\My\Git\parser\Parser\src\parsertools\parsers\sparqlparser.py", line 153, in parseQuery
    result = SPARQLParser.QueryUnit(s, base=base)
  File "C:\Users\brandtp\AppData\Local\My Local Documents\My\Git\parser\Parser\src\parsertools\parsers\sparqlparser.py", line 38, in __init__
    self._checkParsedQuery()
  File "C:\Users\brandtp\AppData\Local\My Local Documents\My\Git\parser\Parser\src\parsertools\parsers\sparqlparser.py", line 106, in _checkParsedQuery
    self._checkExpansion()
  File "C:\Users\brandtp\AppData\Local\My Local Documents\My\Git\parser\Parser\src\parsertools\parsers\sparqlparser.py", line 98, in _checkExpansion
    expansion = getExpansion(iri)
  File "C:\Users\brandtp\AppData\Local\My Local Documents\My\Git\parser\Parser\src\parsertools\parsers\sparqlparser.py", line 226, in getExpansion
    newiristr = rfc3987.resolve(oldiri.getBaseiri(), newiristr)
  File "C:\Users\brandtp\AppData\Local\Programs\Python\Python35\lib\site-packages\rfc3987.py", line 524, in resolve
    B = parse(base, 'IRI')
  File "C:\Users\brandtp\AppData\Local\Programs\Python\Python35\lib\site-packages\rfc3987.py", line 455, in parse
    raise ValueError('%r is not a valid %r.' % (string, rule))
ValueError: '' is not a valid 'IRI'.
```
Bij het weghalen van de '#' in de PREFIX, dus:
```
# query op ontoTemp1A
PREFIX    ontoA:    <http://ts.tno.nl/mediator/1.0/examples/ontoTemp1A>
PREFIX    rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns>
(...)
``` 
loopt het weer als een zonnetje.

Als je de oorspronkelijke '#'-query echter invoert op de [SPARQL Query Validator](http://sparql.org/validate/query), dan krijg je als resultaat:
```
  1 PREFIX  ontoA: <http://ts.tno.nl/mediator/1.0/examples/ontoTemp1A#>
  2 PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
  3 
  4 SELECT  ?p ?v
  5 WHERE
  6   { ?p rdf:type ontoA:Patient .
  7     ?p ontoA:hasTemp ?v
  8     FILTER ( ?v > 37.0 )
  9   }
```

Ik heb hier geen oordeel over, maar merkte het op. 
gr.
     Paul

**Comment by Jeroen537** [comment]
Als ik het goed heb werk je niet met de laatste versie. Daarin is dit verholpen.

Jeroen.

**Comment by plbt5** [comment]
Is bevestigd: In Build 2490 is dit verholpen. Closing issue.
Bedankt.
